### ISSUE TITLE
Feature Request: Use username instead of fullname for editor

### ISSUE THREAD

**Issue by jgonyea** [petira/grav-plugin-stamp#1]
Could an option be provided to save just the username in the editor field instead of fullname?  The fullname isn't a unique field, and could be abused by a user changing it to appear as someone else.

**Comment by petira** [comment]
I plan this option, including the connection to `/user/accounts`, respectively to `/user/data/flex/indexes/accounts.yaml` to obtain full information about the user. The same will be done for the `author` field. I suppose I could put it in the next version sometime in September 2021. It should also use the taxonomy for the `author` and `editor` fields to make them usable for multiple users.

**Comment by petira** [comment]
Done. Download the new Stamp v1.0.3.

I will keep the issue open for now, I still want to finish the connections to accounts and use multiple users.

**Comment by petira** [comment]
Since **Stamp v1.0.4** support for taxonomy type of `author` has been added, so it is now possible to save multiple authors automatically.

**Comment by petira** [comment]
Since **Stamp v1.0.5** Twig variable `users` which contains data from user accounts has been added.

I am closing this issue.
