### ISSUE TITLE
Unable to see the Last modified details on the Page  in GRAV - Learn 2 Git Sync theme

### ISSUE THREAD

**Issue by bachurva** [petira/grav-plugin-stamp#2]
Hi

I am not able to see the date and author details after enabling the plugin.

Am I required to modify the files at  page level?

Kindly confirm the steps to follow after installing the plugin.

Thanks

**Comment by petira** [comment]
Hi,

please specify what and where is not displayed exactly.

The Stamp plugin only edits the `date_modified`, `editor`, and `revision` variables (optionally `date` and `author`) in the frontmatter of the page.

To display the values on the page, you need to use the **Twig code** in the page template.

Take a look at the basic example in [README.md](https://github.com/petira/grav-plugin-stamp/blob/develop/README.md) or the more advanced solution published [here](https://github.com/getgrav/grav/issues/3435#issuecomment-919033368).

**Comment by petira** [comment]
I am closing this issue as resolved. In case of further questions, I will reopen it.
